- Frontend/CloudCure-Angular/src/app/verification/verification.component.css
- Frontend/CloudCure-Angular/src/app/verification/verification.component.html
> Tuned up the verification.html

- Frontend/CloudCure-Angular/src/app/AngularModels/Allergy.ts
- Frontend/CloudCure-Angular/src/app/AngularModels/Assessment.ts
- Frontend/CloudCure-Angular/src/app/AngularModels/Condition.ts
- Frontend/CloudCure-Angular/src/app/AngularModels/Medication.ts
- Frontend/CloudCure-Angular/src/app/AngularModels/Patient.ts
- Frontend/CloudCure-Angular/src/app/AngularModels/Surgery.ts
- Frontend/CloudCure-Angular/src/app/AngularModels/Vitals.ts
- Frontend/CloudCure-Angular/src/app/app.module.ts
- Frontend/CloudCure-Angular/src/app/diagnosis-vitals/diagnosis-vitals.component.html
- Frontend/CloudCure-Angular/src/app/diagnosis-vitals/diagnosis-vitals.component.spec.ts
- Frontend/CloudCure-Angular/src/app/diagnosis-vitals/diagnosis-vitals.component.ts
The angular models are just copied and pasted from the backend models
> Made a basic vitals form and Angular Models

- Backend/Data/Interfaces/IAssessmentRepository.cs
- Backend/Data/Repositories/AssessmentRepository.cs
- Backend/Tests/Diagnosis/AssessmentTest.cs
Passing tests and Assessment repo and irepo
> Assessment test and repo

- Backend/Data/Interfaces/IPatientRepository.cs
- Backend/Data/Repositories/AssessmentRepository.cs
- Backend/Data/Repositories/PatientRepository.cs
- Backend/Tests/Diagnosis/PatientTest.cs
Get patient with nav properties repo, interface, and tests.
> Patient with nav properties

- Backend/WebAPI/Controllers/CovidController.cs
- Backend/WebAPI/Controllers/EmployeeInformationController.cs
- Backend/WebAPI/Controllers/RoleController.cs
- Backend/WebAPI/Controllers/UserController.cs
- Backend/WebAPI/Controllers/VitalsController.cs
Endpoints made uniform and serilog added to UserController
> Uniform endpoints

- Backend/Data/Repositories/EmployeeInformationRepository.cs
- Backend/Data/Repositories/Repository.cs
- Backend/Tests/EmployeeInformationTests.cs
Added more tests for EmployeeInformation
> Employeeinfo

- Backend/Data/Interfaces/IUserRepository.cs
- Backend/Data/Repositories/EmployeeInformationRepository.cs
- Backend/Data/Repositories/UserRepository.cs
- Backend/Tests/EmployeeInformationTests.cs
- Backend/Tests/UserRepoTests.cs
Added UserRepo-specific tests and updated EmployeeInfoRepo/Tests to include new CovidAssesments field
> User repo update

- Backend/Data/Interfaces/IConditionRepository.cs
- Backend/WebAPI/Controllers/AssessmentsController.cs
- Backend/WebAPI/Controllers/ConditionController.cs
- Backend/WebAPI/Controllers/SurgeryController.cs
- Backend/WebAPI/Startup.cs
Fixed the lettering and updated Edit to Update
> Condandsurgcontroller

- Frontend/CloudCure-Angular/src/app/AngularModels/CovidVerify.ts
- Frontend/CloudCure-Angular/src/app/verification/verification.component.html
- Frontend/CloudCure-Angular/src/app/verification/verification.component.ts
Covid verification page will add information to database. UserId is currently hard coded.
> Added covid verification functionality.

- Frontend/CloudCure-Angular/src/app/AngularModels/Vitals.ts
- Frontend/CloudCure-Angular/src/app/diagnosis-vitals/diagnosis-vitals.component.html
- Frontend/CloudCure-Angular/src/app/diagnosis-vitals/diagnosis-vitals.component.ts
I connected the vitals service to its form
Currently, its only adding to Patient ID 2 since I'm not sure how we are routing the pages in order to properly retrieve the current patient ID, making it dynamic.
> able to add vitals to DB

- Frontend/CloudCure-Angular/src/app/profile/profile.component.ts
> Joshua Told Me 2

- Backend/Tests/Controller/AssessmentsControllerTest.cs
Added tests for the AssessmentController
> AssessmentController tests added

- Frontend/CloudCure-Angular/src/app/patient/patient.component.css
- Frontend/CloudCure-Angular/src/app/patient/patient.component.html
- Frontend/CloudCure-Angular/src/app/patient/patient.component.ts
> Formatted Patient Registry Page

- Backend/Tests/Controller/EmployeeInformationControllerTests.cs
Added testing for the EmployeeInformationController
> Added tests for EmployeeInformationController

- Backend/Tests/Controller/PatientControllerTests.cs
> Added PatientController tests

- Backend/Tests/Controller/MedicationControllerTests.cs
- Backend/Tests/Controller/VitalsControllerTest.cs
- Backend/WebAPI/Controllers/MedicationController.cs
- Backend/WebAPI/Controllers/VitalsController.cs
More testing for vitals controller and medication going off what we need for sonarcloud
> Controller Testing

- Backend/Tests/Controller/RoleControllerTests.cs
> Added RoleController tests

- Frontend/CloudCure-Angular/src/app/app.module.ts
- Frontend/CloudCure-Angular/src/app/list-patient/list-patient.component.css
- Frontend/CloudCure-Angular/src/app/list-patient/list-patient.component.html
- Frontend/CloudCure-Angular/src/app/list-patient/list-patient.component.spec.ts
- Frontend/CloudCure-Angular/src/app/list-patient/list-patient.component.ts
> To The Homies

- Frontend/CloudCure-Angular/src/app/app.module.ts
- Frontend/CloudCure-Angular/src/app/diagnosis-medication/diagnosis-medication.component.html
- Frontend/CloudCure-Angular/src/app/diagnosis-medication/diagnosis-medication.component.ts
Same as allergy component. Hardcoded to patient 1, can be changed later. Also, I didn't check to see if it got saved in the DB. If it doesn't, just send the request back to me and I'll fix it
> adding medication functionality implemented

- Backend/WebAPI/Controllers/PatientController.cs
Changed line 45 and removed second method
> Getpatientwithnavcontroller

- Backend/Tests/RepositoryTests/AllergyRepoTests.cs
Added tests for the AllergyRepository methods
> Added tests for AllergyRepository

- Backend/Tests/Controller/EmployeeInformationControllerTests.cs
- Backend/Tests/Controller/RoleControllerTests.cs
- Backend/Tests/Controller/UserControllerTests.cs
- Backend/Tests/RepositoryTests/RoleRepoTests.cs
Added some more tests to raise test coverage
> More role controller tests

- Backend/Tests/Controller/ConditionControllerTest.cs
- Backend/Tests/Diagnosis/SurgeryTest.cs
This is actually Surgery Repo tests.
> Moreconditioncontrollertest

- Frontend/CloudCure-Angular/src/app/app.module.ts
- Frontend/CloudCure-Angular/src/app/login/login.component.ts
Please check to let me know if this is okay Colin. Thank You!
> added auth0 refresh token

- Backend/Data/Repositories/AllergyRepository.cs
- Backend/Tests/Controller/AllergyControllerTest.cs
- Backend/Tests/Controller/AssessmentsControllerTest.cs
- Backend/Tests/Controller/ConditionControllerTest.cs
- Backend/Tests/Controller/CovidControllerTest.cs
- Backend/Tests/Controller/MedicationControllerTests.cs
- Backend/Tests/Controller/PatientControllerTests.cs
- Backend/Tests/Controller/RoleControllerTests.cs
- Backend/Tests/Controller/SurgeryControllerTest.cs
- Backend/Tests/Controller/UserControllerTests.cs
- Backend/Tests/Diagnosis/PatientTest.cs
- Backend/WebAPI/Controllers/AllergyController.cs
- Backend/WebAPI/Controllers/AssessmentsController.cs
- Backend/WebAPI/Controllers/ConditionController.cs
- Backend/WebAPI/Controllers/MedicationController.cs
- Backend/WebAPI/Controllers/PatientController.cs
- Backend/WebAPI/Controllers/RoleController.cs
- Backend/WebAPI/Controllers/SurgeryController.cs
- Backend/WebAPI/Controllers/UserController.cs
Updated controller tests to test catch blocks. Also did some minor formatting fixes on some other files.
> Dannys branch

- Backend/Tests/RepositoryTests/CovidRepoTests.cs
> Added tests for catch block

- Frontend/CloudCure-Angular/src/app/AngularModels/CovidVerify.ts
- Frontend/CloudCure-Angular/src/app/patient/patient.component.ts
- Frontend/CloudCure-Angular/src/app/verification/verification.component.ts
Quality GRADE A Covid Verification Form - grabs PatientId via Patient Service...now..
> Angels branch

- Frontend/CloudCure-Angular/src/app/home/home.component.css
- Frontend/CloudCure-Angular/src/app/home/home.component.html
- Frontend/CloudCure-Angular/src/app/list-patient/list-patient.component.css
- Frontend/CloudCure-Angular/src/app/list-patient/list-patient.component.html
- Frontend/CloudCure-Angular/src/app/list-patient/list-patient.component.ts
> Altered Home Cards and Routed Patient Profile

- Backend/Tests/RepositoryTests/EmployeeInfoRepoTests.cs
> Added more tests

- Frontend/CloudCure-Angular/src/app/app.module.ts
- Frontend/CloudCure-Angular/src/app/verification/verification.component.css
- Frontend/CloudCure-Angular/src/app/verification/verification.component.html
- Frontend/CloudCure-Angular/src/app/verification/verification.component.ts
Radio buttons increased in size. Question(s) titles made bold and added  more spacing between buttons.
> Big Buttons

- Frontend/CloudCure-Angular/src/app/patient-view/patient-view.component.css
- Frontend/CloudCure-Angular/src/app/patient-view/patient-view.component.html
- Frontend/CloudCure-Angular/src/app/patient-view/patient-view.component.ts
> Patient-View

- Frontend/CloudCure-Angular/src/app/diagnosis-vitals/diagnosis-vitals.component.css
- Frontend/CloudCure-Angular/src/app/diagnosis-vitals/diagnosis-vitals.component.html
- Frontend/CloudCure-Angular/src/app/diagnosis-vitals/diagnosis-vitals.component.ts
> Added buttons to diagnosis/vitals page

- Backend/Tests/ModelTests/PatientModelTests.cs
Added complete testing for Patient model
> Added complete PatientModel testing

- Backend/Tests/Controller/VitalsControllerTest.cs
- Backend/Tests/ModelTests/DiagnosisModelTests.cs
> Dannys new branch

- Frontend/CloudCure-Angular/src/app/diagnosis-vitals/diagnosis-vitals.component.ts
> changed routing

- Backend/Tests/Controller/DiagnosisControllerTest.cs
> Diagnosis Controller tests

- Frontend/CloudCure-Angular/src/app/diagnosis-vitals/diagnosis-vitals.component.html
- Frontend/CloudCure-Angular/src/app/diagnosis-vitals/diagnosis-vitals.component.ts
- Frontend/CloudCure-Angular/src/app/list-patient/list-patient.component.html
- Frontend/CloudCure-Angular/src/app/services/vitals.service.ts
- Frontend/CloudCure-Angular/src/app/view-diagnosis/view-diagnosis.component.css
> Submit btn jake

- Frontend/CloudCure-Angular/src/app/home/home.component.html
- Frontend/CloudCure-Angular/src/app/list-patient/list-patient.component.css
- Frontend/CloudCure-Angular/src/app/list-patient/list-patient.component.html
- Frontend/CloudCure-Angular/src/app/list-patient/list-patient.component.ts
- Frontend/CloudCure-Angular/src/app/patient-view/patient-view.component.css
- Frontend/CloudCure-Angular/src/app/patient-view/patient-view.component.html
- Frontend/CloudCure-Angular/src/app/patient-view/patient-view.component.ts
added buttons and fixed styling
> added buttons and fixed sizing

- Frontend/CloudCure-Angular/src/app/patient-view/patient-view.component.html
- Frontend/CloudCure-Angular/src/app/patient/patient.component.html
HTML only to not mess up anything. I believe those were the only instances, but I might have missed something
> Changed conditions to Family Medical History

- Backend/Tests/ModelTests/DiagnosisModelTests.cs
- Backend/Tests/RepositoryTests/EmployeeInfoRepoTests.cs
- Backend/WebAPI/Controllers/AllergyController.cs
Hopefully this will work to fix code smells and then I can fix the rest
> Dannys other branch

- Frontend/CloudCure-Angular/src/app/finalized-diagnosis-view/finalized-diagnosis-view.component.html
My bad. I was triple checking and I found a conditions that I missed. Hopefully, that was the last one
> I missed a conditions

- Backend/Tests/Controller/AllergyControllerTest.cs
- Backend/Tests/Controller/AssessmentsControllerTest.cs
- Backend/Tests/Controller/ConditionControllerTest.cs
Updated some tests for better coverage
> Updated tests for more coverage

- Frontend/CloudCure-Angular/src/app/assessment/assessment.component.css
- Frontend/CloudCure-Angular/src/app/assessment/assessment.component.html
- Frontend/CloudCure-Angular/src/app/body-clicker/body-clicker.component.scss
Assessment Form - Body Clicker refined
> Angel branch

- Backend/Tests/Controller/AssessmentsControllerTest.cs
- Backend/WebAPI/Controllers/AssessmentsController.cs
I missed one tiny code smell, but this should be my last pull request. I promise!
> Fixed last code smell

- Frontend/CloudCure-Angular/src/app/patient-view/patient-view.component.css
- Frontend/CloudCure-Angular/src/app/patient-view/patient-view.component.html
- Frontend/CloudCure-Angular/src/app/profile/profile.component.css
- Frontend/CloudCure-Angular/src/app/profile/profile.component.html
- Frontend/CloudCure-Angular/src/app/view-diagnosis/view-diagnosis.component.css
- Frontend/CloudCure-Angular/src/app/view-diagnosis/view-diagnosis.component.html
> Updated Patient View, View-Diagnosis

- Backend/Tests/Controller/EmployeeInformationControllerTests.cs
- Backend/WebAPI/Controllers/EmployeeInformationController.cs
VerifyEmail test had the wrong expected response code so that's why it was failing. Fixed for better code coverage and no code smells
> Fixed VerifyEmail test

- login.html
> Added Auht0 Script For Future Batches

- Frontend/CloudCure-Angular/src/app/patient-view/patient-view.component.html
fixed the bug where If a patient had a current diagnosis being worked on, no previous diagnosis would display.
> fixed bug on displaying diagnosis
